package de.lambda9.ready2race.backend.app.webDAV.entity


enum class WebDAVExportType {
    INVOICES,
    REGISTRATION_RESULTS,
    DOCUMENTS,
    RESULTS,
    START_LISTS,
    DB_USERS,
    DB_PARTICIPANTS,
    DB_BANK_ACCOUNTS,
    DB_CONTACT_INFORMATION,
    DB_EMAIL_INDIVIDUAL_TEMPLATES,
    DB_EVENT_DOCUMENT_TYPES,
    DB_MATCH_RESULT_IMPORT_CONFIGS,
    DB_STARTLIST_EXPORT_CONFIGS,
    DB_WORK_TYPES,
    DB_PARTICIPANT_REQUIREMENTS,
    DB_RATING_CATEGORIES,
    DB_COMPETITION_CATEGORIES,
    DB_FEES,
    DB_NAMED_PARTICIPANTS,
    DB_COMPETITION_SETUP_TEMPLATES,
    DB_COMPETITION_TEMPLATES,
    DB_EVENT,
    DB_COMPETITION;
}