package de.lambda9.ready2race.backend.app.email.entity

enum class EmailTemplateKey {
    USER_REGISTRATION,
    USER_INVITATION,
    USER_RESET_PASSWORD,
    EVENT_REGISTRATION_CONFIRMATION,
    EVENT_REGISTRATION_INVOICE,
    PARTICIPANT_CHALLENGE_REGISTERED,
}