// This file is auto-generated by @hey-api/openapi-ts

export type AppUserProperties = {
    email: string
    firstname: string
    lastname: string
    roles: Array<string>
}

export type AppUserResponse = {
    id: string
    properties: AppUserProperties
}

export type EventDayDto = {
    id: string
    eventId?: string
    properties: EventDayProperties
}

export type EventDayProperties = {
    date: string
    name?: string
    description?: string
}

export type EventDayRequest = {
    properties: EventDayProperties
}

export type EventDto = {
    id: string
    properties: EventProperties
}

export type EventProperties = {
    name: string
    description?: string
    location?: string
    registrationAvailableFrom?: string
    registrationAvailableTo?: string
    paymentDueDate?: string
    invoicePrefix?: string
}

export type EventRequest = {
    properties: EventProperties
}

export type GetEventDayPageResponse = {
    data: Array<EventDayDto>
    pagination: Pagination
}

export type GetEventDayResponse = {
    dto: EventDayDto
}

export type GetEventPageResponse = {
    data: Array<EventDto>
    pagination: Pagination
}

export type GetEventResponse = {
    dto: EventDto
}

export type GetRacePageResponse = {
    data: Array<RaceDto>
    pagination: Pagination
}

export type GetRaceResponse = {
    dto: RaceDto
}

export type LoginRequest = {
    email: string
    password: string
}

export type LoginResponse = {
    privilegesGlobal: Array<Privilege>
    privilegesBound: Array<Privilege>
}

export type NamedParticipantDto = {
    name: string
    description?: string
    required: boolean
}

export type NamedParticipantWithCountDto = {
    name: string
    description?: string
    required: boolean
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
}

export type Order = {
    field?: string
    direction?: 'ASC' | 'DESC'
}

export type direction = 'ASC' | 'DESC'

export type Pagination = {
    total: number
    limit: number
    offset: number
    sort: Array<Order>
}

/**
 * Page size for pagination
 */
export type Parameterlimit = number

/**
 * Result offset for pagination
 */
export type Parameteroffset = number

/**
 * Filter result with space-separated search terms for pagination
 */
export type Parametersearch = string

/**
 * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
 */
export type Parametersort = string

export type Privilege =
    | 'USER_VIEW'
    | 'USER_EDIT'
    | 'ROLE_VIEW'
    | 'ROLE_EDIT'
    | 'EVENT_EDIT'
    | 'EVENT_VIEW'

export type RaceDto = {
    id: string
    event: string
    raceProperties: RacePropertiesWithNamedParticipantListDto
    template?: string
}

export type RacePropertiesDto = {
    identifier: string
    name: string
    shortName?: string
    description?: string
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
    participationFee: number
    rentalFee: number
    raceCategory?: string
}

export type RacePropertiesHasNamedParticipantDto = {
    namedParticipant: string
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
}

export type RacePropertiesWithNamedParticipantListDto = {
    raceProperties: RacePropertiesDto
    namedParticipantList: Array<NamedParticipantWithCountDto>
}

export type RaceRequest = {
    raceProperties: RacePropertiesDto
    template?: string
    namedParticipantList: Array<RacePropertiesHasNamedParticipantDto>
}

export type UserLoginData = {
    body: LoginRequest
}

export type UserLoginResponse = LoginResponse

export type UserLoginError = string

export type CheckUserLoginResponse = LoginResponse | void

export type CheckUserLoginError = string

export type UserLogoutResponse = void

export type UserLogoutError = string

export type AddEventData = {
    body: EventRequest
}

export type AddEventResponse = string

export type AddEventError = string

export type GetEventsData = {
    query: {
        /**
         * Page size for pagination
         */
        limit: number
        /**
         * Result offset for pagination
         */
        offset: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort: string
    }
}

export type GetEventsResponse = GetEventPageResponse

export type GetEventsError = string

export type GetEventResponse2 = GetEventResponse

export type GetEventError = string

export type UpdateEventData = {
    body: EventRequest
}

export type UpdateEventResponse = void

export type UpdateEventError = string

export type DeleteEventResponse = void

export type DeleteEventError = string

export type AddEventDayData = {
    body: EventDayRequest
}

export type AddEventDayResponse = string

export type AddEventDayError = string

export type GetEventDaysData = {
    query: {
        /**
         * Page size for pagination
         */
        limit: number
        /**
         * Result offset for pagination
         */
        offset: number
        /**
         * Optional parameter that filters by raceId
         */
        raceId?: string
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort: string
    }
}

export type GetEventDaysResponse = GetEventDayPageResponse

export type GetEventDaysError = string

export type GetEventDayResponse2 = GetEventDayResponse

export type GetEventDayError = string

export type UpdateEventDayData = {
    body: EventDayRequest
}

export type UpdateEventDayResponse = void

export type UpdateEventDayError = string

export type DeleteEventDayResponse = void

export type DeleteEventDayError = string

export type AddRaceData = {
    body: RaceRequest
}

export type AddRaceResponse = string

export type AddRaceError = string

export type GetRacesData = {
    query: {
        /**
         * Page size for pagination
         */
        limit: number
        /**
         * Result offset for pagination
         */
        offset: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort: string
    }
}

export type GetRacesResponse = GetRacePageResponse

export type GetRacesError = string

export type GetRaceResponse2 = GetRaceResponse

export type GetRaceError = string

export type UpdateRaceData = {
    body: RaceRequest
}

export type UpdateRaceResponse = void

export type UpdateRaceError = string

export type DeleteRaceResponse = void

export type DeleteRaceError = string

export type AddNamedParticipantData = {
    body: NamedParticipantDto
}

export type AddNamedParticipantResponse = void

export type AddNamedParticipantError = string

export type GetNamedParticipantsResponse = Array<NamedParticipantDto>

export type GetNamedParticipantsError = string

export type UpdateNamedParticipantData = {
    body: NamedParticipantDto
}

export type UpdateNamedParticipantResponse = void

export type UpdateNamedParticipantError = string

export type DeleteNamedParticipantResponse = void

export type DeleteNamedParticipantError = string

export type AddRaceCategoryData = {
    body: string
}

export type AddRaceCategoryResponse = void

export type AddRaceCategoryError = string

export type GetRaceCategoryResponse = Array<string>

export type GetRaceCategoryError = string

export type UpdateRaceCategoryData = {
    body: string
}

export type UpdateRaceCategoryResponse = void

export type UpdateRaceCategoryError = string

export type DeleteRaceCategoryResponse = void

export type DeleteRaceCategoryError = string
