// This file is auto-generated by @hey-api/openapi-ts

export type AcceptInvitationRequest = {
    token: string
    password: string
}

export type Action = 'CREATE' | 'READ' | 'UPDATE' | 'DELETE'

export type ApiError = {
    status: {
        value: number
        description: string
    }
    message: string
    errorCode?: ErrorCode
}

export type AppUserDto = {
    id: string
    email: string
    firstname: string
    lastname: string
    roles: Array<RoleDto>
}

export type AppUserInvitationDto = {
    id: string
    email: string
    firstname: string
    lastname: string
    language: EmailLanguage
    expiresAt: string
    createdAt: string
    assignedEmail?: AssignedEmailDto
    roles: Array<RoleDto>
    createdBy?: AppUserNameDto
}

export type AppUserNameDto = {
    id: string
    firstname: string
    lastname: string
}

export type AppUserRegistrationDto = {
    id: string
    email: string
    firstname: string
    lastname: string
    language: EmailLanguage
    expiresAt: string
    createdAt: string
    assignedEmail?: AssignedEmailDto
}

export type AssignBankAccountRequest = {
    bankAccount?: string
    event?: string
}

export type AssignCompetitionsToDayRequest = {
    competitions: Array<string>
}

export type AssignContactInformationRequest = {
    contact?: string
    event?: string
}

export type AssignDaysToCompetitionRequest = {
    days: Array<string>
}

export type AssignDocumentTemplateRequest = {
    template?: string
    event?: string
}

export type AssignedBankAccountDto = {
    assigned?: BankAccountDto
}

export type AssignedContactInformationDto = {
    assigned?: ContactInformationDto
}

export type AssignedEmailDto = {
    recipient: string
    sentAt?: string
    lastErrorAt?: string
    lastError?: string
}

export type AssignedTemplateId = {
    value?: string
}

export type BadRequestError = ApiError & {
    details?: {
        validExample?: unknown
    }
}

export type BankAccountDto = {
    id: string
    holder: string
    iban: string
    bic: string
    bank: string
}

export type BankAccountRequest = {
    holder: string
    iban: string
    bic: string
    bank: string
}

export type CaptchaDto = {
    id: string
    imgSrc: string
    solutionMin: number
    solutionMax: number
    handleToHeightRatio: number
    start: number
}

export type ClubDto = {
    id: string
    name: string
    createdAt: string
    updatedAt: string
}

export type ClubSearchDto = {
    id: string
    name: string
}

export type ClubUpsertDto = {
    name: string
}

export type CompetitionCategoryDto = {
    id: string
    name: string
    description?: string
}

export type CompetitionCategoryRequest = {
    name: string
    description?: string
}

export type CompetitionDto = {
    id: string
    event: string
    properties: CompetitionPropertiesDto
    template?: string
    registrationCount?: number
}

export type CompetitionPropertiesDto = {
    identifier: string
    name: string
    shortName?: string
    description?: string
    competitionCategory?: CompetitionCategoryDto
    namedParticipants: Array<NamedParticipantForCompetitionDto>
    fees: Array<FeeForCompetitionDto>
}

export type CompetitionPropertiesRequestDto = {
    identifier: string
    name: string
    shortName?: string
    description?: string
    competitionCategory?: string
    namedParticipants: Array<NamedParticipantForCompetitionRequestDto>
    fees: Array<FeeForCompetitionRequestDto>
}

export type CompetitionRegistrationFeeDto = {
    feeId: string
    feeName: string
}

export type CompetitionRegistrationNamedParticipantDto = {
    namedParticipantId: string
    namedParticipantName: string
    participants: Array<ParticipantForEventDto>
}

export type CompetitionRegistrationNamedParticipantUpsertDto = {
    namedParticipantId: string
    participantIds: Array<string>
}

export type CompetitionRegistrationSingleUpsertDto = {
    competitionId: string
    optionalFees?: Array<string>
}

export type CompetitionRegistrationTeamDto = {
    id: string
    name: string
    clubId: string
    clubName: string
    optionalFees: Array<CompetitionRegistrationFeeDto>
    namedParticipants: Array<CompetitionRegistrationNamedParticipantDto>
    updatedAt: string
    createdAt: string
}

export type CompetitionRegistrationTeamUpsertDto = {
    id: string
    clubId?: string
    optionalFees?: Array<string>
    namedParticipants?: Array<CompetitionRegistrationNamedParticipantUpsertDto>
}

export type CompetitionRegistrationUpsertDto = {
    competitionId: string
    teams?: Array<CompetitionRegistrationTeamUpsertDto>
}

export type CompetitionRequest = {
    properties?: CompetitionPropertiesRequestDto
    template?: string
}

export type CompetitionSetupDto = {
    rounds: Array<CompetitionSetupRoundDto>
}

export type CompetitionSetupGroupDto = {
    weighting: number
    teams?: number
    name?: string
    matches: Array<CompetitionSetupMatchDto>
    participants: Array<number>
}

export type CompetitionSetupGroupStatisticEvaluationDto = {
    name: string
    priority: number
    rankByBiggest: boolean
    ignoreBiggestValues: number
    ignoreSmallestValues: number
    asAverage: boolean
}

export type CompetitionSetupMatchDto = {
    weighting: number
    teams?: number
    name?: string
    participants: Array<number>
    executionOrder: number
    startTimeOffset?: number
}

export type CompetitionSetupPlaceDto = {
    roundOutcome: number
    place: number
}

export type CompetitionSetupRoundDto = {
    name: string
    required: boolean
    matches?: Array<CompetitionSetupMatchDto>
    groups?: Array<CompetitionSetupGroupDto>
    statisticEvaluations?: Array<CompetitionSetupGroupStatisticEvaluationDto>
    useDefaultSeeding: boolean
    placesOption: 'EQUAL' | 'ASCENDING' | 'CUSTOM'
    places?: Array<CompetitionSetupPlaceDto>
}

export type placesOption = 'EQUAL' | 'ASCENDING' | 'CUSTOM'

export type CompetitionSetupTemplateDto = {
    id: string
    name: string
    description?: string
    rounds: Array<CompetitionSetupRoundDto>
}

export type CompetitionSetupTemplateRequest = {
    name: string
    description?: string
    rounds: Array<CompetitionSetupRoundDto>
}

export type CompetitionTemplateDto = {
    id: string
    properties: CompetitionPropertiesDto
}

export type CompetitionTemplateRequest = {
    properties: CompetitionPropertiesRequestDto
}

export type ContactInformationDto = {
    id: string
    name: string
    addressZip: string
    addressCity: string
    addressStreet: string
    email: string
}

export type ContactInformationRequest = {
    name: string
    addressZip: string
    addressCity: string
    addressStreet: string
    email: string
}

export type DocumentTemplateDto = {
    id: string
    name: string
    pagePaddingTop?: number
    pagePaddingLeft?: number
    pagePaddingRight?: number
    pagePaddingBottom?: number
}

export type DocumentTemplateRequest = {
    pagePaddingTop?: number
    pagePaddingLeft?: number
    pagePaddingRight?: number
    pagePaddingBottom?: number
}

export type DocumentType = 'INVOICE' | 'REGISTRATION_REPORT'

export type DocumentTypeDto = {
    type: DocumentType
    assignedTemplate?: AssignedTemplateId
}

export type Duplicate = {
    value: unknown
    count: number
}

export type EmailLanguage = 'DE' | 'EN'

export type ErrorCode = 'CAPTCHA_WRONG' | 'EMAIL_IN_USE' | 'CANNOT_ASSIGN_ROLES'

export type EventDayDto = {
    id: string
    event: string
    date: string
    name?: string
    description?: string
}

export type EventDayRequest = {
    date: string
    name?: string
    description?: string
}

export type EventDocumentDto = {
    id: string
    documentType?: EventDocumentTypeDto
    name: string
    createdAt: string
    createdBy?: AppUserNameDto
    updatedAt: string
    updatedBy?: AppUserNameDto
}

export type EventDocumentRequest = {
    documentType?: string
}

export type EventDocumentTypeDto = {
    id: string
    name: string
    description?: string
    required: boolean
    confirmationRequired: boolean
}

export type EventDocumentTypeRequest = {
    name: string
    description?: string
    required: boolean
    confirmationRequired: boolean
}

export type EventDto = {
    id: string
    name: string
    description?: string
    location?: string
    registrationAvailableFrom?: string
    registrationAvailableTo?: string
    invoicePrefix?: string
    published?: boolean
    invoicesProduced?: string
    paymentDueBy?: string
}

export type EventPublicDto = {
    id: string
    name: string
    description?: string
    location?: string
    registrationAvailableFrom?: string
    registrationAvailableTo?: string
    createdAt: string
    competitionCount: number
    eventFrom?: string
    eventTo?: string
}

export type EventRegistrationCompetitionDto = {
    id: string
    identifier: string
    name: string
    shortName?: string
    description?: string
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
    competitionCategory: string
    namedParticipant?: Array<EventRegistrationNamedParticipantDto>
    fees?: Array<EventRegistrationFeeDto>
    days: Array<string>
}

export type EventRegistrationDayDto = {
    id: string
    date: string
    name?: string | null
    description?: string | null
}

export type EventRegistrationDocumentFileDto = {
    id: string
    name: string
}

export type EventRegistrationDocumentTypeDto = {
    id: string
    name: string
    description?: string
    confirmationRequired?: boolean
    files: Array<EventRegistrationDocumentFileDto>
}

export type EventRegistrationFeeDto = {
    id: string
    label: string
    description?: string | null
    required: boolean
    amount: number
}

export type EventRegistrationInfoDto = {
    name: string
    description?: string
    location?: string
    days: Array<EventRegistrationDayDto>
    documentTypes?: Array<EventRegistrationDocumentTypeDto>
    competitionsSingle: Array<EventRegistrationCompetitionDto>
    competitionsTeam: Array<EventRegistrationCompetitionDto>
}

export type EventRegistrationNamedParticipantDto = {
    id: string
    name: string
    description?: string
    required?: boolean
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
}

export type EventRegistrationParticipantUpsertDto = {
    id: string
    isNew?: boolean
    hasChanged?: boolean
    firstname: string
    lastname: string
    year?: number | null
    gender: Gender
    external?: boolean | null
    externalClubName?: string | null
    competitionsSingle?: Array<CompetitionRegistrationSingleUpsertDto>
}

export type EventRegistrationTemplateDto = {
    info: EventRegistrationInfoDto
    upsertableRegistration: EventRegistrationUpsertDto
}

export type EventRegistrationUpsertDto = {
    participants: Array<EventRegistrationParticipantUpsertDto>
    competitionRegistrations: Array<CompetitionRegistrationUpsertDto>
    message?: string
}

export type EventRegistrationViewDto = {
    id: string
    createdAt: string
    message?: string
    updatedAt: string
    eventId: string
    eventName: string
    clubId: string
    clubName: string
    competitionRegistrationCount: number
    participantCount: number
}

export type EventRequest = {
    name: string
    description?: string
    location?: string
    registrationAvailableFrom?: string
    registrationAvailableTo?: string
    invoicePrefix?: string
    published: boolean
    paymentDueBy?: string
}

export type FeeDto = {
    id: string
    name: string
    description?: string
}

export type FeeForCompetitionDto = {
    id: string
    name: string
    description?: string
    required: boolean
    amount: string
}

export type FeeForCompetitionRequestDto = {
    fee: string
    required: boolean
    amount: string
}

export type FeeRequest = {
    name: string
    description?: string
}

export type Gender = 'M' | 'F' | 'D'

export type Invalid =
    | string
    | {
          field: string
          error: Invalid
      }
    | {
          errorPositions: unknown
      }
    | Duplicate
    | {
          duplicates: Array<Duplicate>
      }
    | {
          value: string
          pattern: string
      }
    | {
          allOf: Array<Invalid>
      }
    | {
          anyOf: Array<Invalid>
      }
    | {
          oneOf: Array<
              | Invalid
              | {
                    [key: string]: unknown
                }
          >
      }

export type InviteRequest = {
    email: string
    firstname: string
    lastname: string
    language: EmailLanguage
    roles: Array<string>
    admin?: boolean
    callbackUrl: string
}

export type LoginDto = {
    id: string
    privileges: Array<PrivilegeDto>
    clubId?: string
}

export type LoginRequest = {
    email: string
    password: string
}

export type NamedParticipantDto = {
    id: string
    name: string
    description?: string
}

export type NamedParticipantForCompetitionDto = {
    id: string
    name: string
    description?: string
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
}

export type NamedParticipantForCompetitionRequestDto = {
    namedParticipant: string
    countMales: number
    countFemales: number
    countNonBinary: number
    countMixed: number
}

export type NamedParticipantRequest = {
    name: string
    description?: string
}

export type Order = {
    field: string
    direction: 'ASC' | 'DESC'
}

export type direction = 'ASC' | 'DESC'

export type Pagination = {
    total: number
    limit: number
    offset: number
    sort: Array<Order>
    search: string
}

/**
 * Captcha challenge id
 */
export type Parameterchallenge = string

export type ParametercompetitionId = string

export type ParametercompetitionRegistrationId = string

export type ParametereventDayId = string

export type ParametereventId = string

/**
 * Captcha solution
 */
export type Parameterinput = number

/**
 * Page size for pagination
 */
export type Parameterlimit = number

/**
 * Result offset for pagination
 */
export type Parameteroffset = number

/**
 * Filter result with space-separated search terms for pagination
 */
export type Parametersearch = string

/**
 * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
 */
export type Parametersort = string

export type ParticipantDto = {
    id: string
    firstname: string
    lastname: string
    year?: number | null
    gender: Gender
    phone?: string | null
    external?: boolean | null
    externalClubName?: string | null
    usedInRegistration: boolean
    createdAt: string
    updatedAt: string
}

export type ParticipantForEventDto = {
    id: string
    clubId: string
    clubName: string
    firstname: string
    lastname: string
    year?: number | null
    gender: Gender
    external?: boolean | null
    externalClubName?: string | null
    participantRequirementsChecked?: Array<ParticipantRequirementReducedDto>
}

export type ParticipantRequirementCheckForEventConfigDto = {
    requirementId: string
    separator?: string
    charset?: string
    firstnameColName: string
    lastnameColName: string
    yearsColName?: string
    clubColName?: string
    requirementColName?: string
    requirementIsValidValue?: string
}

export type ParticipantRequirementCheckForEventUpsertDto = {
    requirementId: string
    approvedParticipants: Array<string>
}

export type ParticipantRequirementDto = {
    id: string
    name: string
    description?: string
    optional: boolean
}

export type ParticipantRequirementForEventDto = {
    id: string
    name: string
    description?: string
    optional: boolean
    active: boolean
}

export type ParticipantRequirementReducedDto = {
    id: string
    name: string
}

export type ParticipantRequirementUpsertDto = {
    name: string
    description?: string
    optional?: boolean
}

export type ParticipantUpsertDto = {
    firstname: string
    lastname: string
    year?: number | null
    gender: Gender
    phone?: string | null
    external?: boolean | null
    externalClubName?: string | null
}

export type PasswordResetInitRequest = {
    email: string
    language: EmailLanguage
    callbackUrl: string
}

export type PasswordResetRequest = {
    password: string
}

export type Privilege = {
    action: Action
    resource: Resource
    scope: Scope
}

export type PrivilegeDto = {
    id: string
    action: Action
    resource: Resource
    scope: Scope
}

export type RegisterRequest = {
    email: string
    password: string
    firstname: string
    lastname: string
    clubname: string
    language: EmailLanguage
    callbackUrl: string
}

export type Resource = 'USER' | 'EVENT' | 'CLUB' | 'REGISTRATION'

export type RoleDto = {
    id: string
    name: string
    description?: string
    privileges: Array<PrivilegeDto>
}

export type RoleRequest = {
    name: string
    description?: string
    privileges: Array<string>
}

export type Scope = 'OWN' | 'GLOBAL'

export type TaskDto = {
    id: string
    event: string
    eventName: string
    name: string
    dueDate?: string | null
    description?: string | null
    remark?: string | null
    state: TaskState
    createdAt: string
    updatedAt: string
    responsibleUsers: Array<AppUserNameDto>
}

export type TaskState = 'OPEN' | 'IN_PROGRESS' | 'DONE' | 'CANCELED'

export type TaskUpsertDto = {
    name: string
    dueDate?: string | null
    description?: string | null
    remark?: string | null
    state: TaskState
    responsibleUsers: Array<string>
}

export type TooManyRequestsError = ApiError & {
    details: {
        retryAfter: number
    }
}

export type UnprocessableEntityError = ApiError & {
    details:
        | {
              reason: Invalid
          }
        | {
              result: Invalid
          }
}

export type UpdateAppUserRequest = {
    firstname: string
    lastname: string
    roles: Array<string>
}

export type VerifyRegistrationRequest = {
    token: string
}

export type WorkShiftUpsertDto = {
    workType: string
    timeFrom: string
    timeTo: string
    minUser: number
    maxUser?: number
    remark?: string
    assignedUsers: Array<string>
}

export type WorkShiftWithAssignedUsersDto = {
    id: string
    title: string
    event: string
    timeFrom: string
    timeTo: string
    eventName: string
    workType: string
    workTypeName?: string
    remark?: string
    minUser: number
    maxUser?: number
    createdAt: string
    updatedAt: string
    assignedUsers: Array<AppUserNameDto>
}

export type WorkTypeDto = {
    id: string
    name: string
    description?: string | null
    color?: string
    minUser: number
    maxUser?: number
    createdAt: string
    updatedAt: string
}

export type WorkTypeUpsertDto = {
    name: string
    description?: string
    color?: string
    minUser: number
    maxUser?: number
}

export type UserLoginData = {
    body: LoginRequest
}

export type UserLoginResponse = LoginDto

export type UserLoginError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError
    | TooManyRequestsError

export type CheckUserLoginResponse = LoginDto | void

export type CheckUserLoginError = ApiError

export type UserLogoutResponse = void

export type UserLogoutError = ApiError

export type GetPrivilegesResponse = Array<PrivilegeDto>

export type GetPrivilegesError = BadRequestError | ApiError

export type GetUsersData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Optional parameter that filters users that have a club assigned to them
         */
        noClub?: boolean
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetUsersResponse = {
    data: Array<AppUserDto>
    pagination: Pagination
}

export type GetUsersError = BadRequestError | ApiError | UnprocessableEntityError

export type GetUserData = {
    path: {
        userId: string
    }
}

export type GetUserResponse = AppUserDto

export type GetUserError = BadRequestError | ApiError

export type UpdateUserData = {
    body: UpdateAppUserRequest
    path: {
        userId: string
    }
}

export type UpdateUserResponse = void

export type UpdateUserError = BadRequestError | ApiError | UnprocessableEntityError

export type RegisterUserData = {
    body: RegisterRequest
    query: {
        /**
         * Captcha challenge id
         */
        challenge: string
        /**
         * Captcha solution
         */
        input: number
    }
}

export type RegisterUserResponse = void

export type RegisterUserError = BadRequestError | ApiError | UnprocessableEntityError

export type GetRegistrationsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetRegistrationsResponse = {
    data: Array<AppUserRegistrationDto>
    pagination: Pagination
}

export type GetRegistrationsError = BadRequestError | ApiError | UnprocessableEntityError

export type VerifyUserRegistrationData = {
    body: VerifyRegistrationRequest
}

export type VerifyUserRegistrationResponse = unknown

export type VerifyUserRegistrationError = BadRequestError | ApiError | UnprocessableEntityError

export type InviteUserData = {
    body: InviteRequest
}

export type InviteUserResponse = void

export type InviteUserError = BadRequestError | ApiError | UnprocessableEntityError

export type GetInvitationsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetInvitationsResponse = {
    data: Array<AppUserInvitationDto>
    pagination: Pagination
}

export type GetInvitationsError = BadRequestError | ApiError | UnprocessableEntityError

export type AcceptUserInvitationData = {
    body: AcceptInvitationRequest
}

export type AcceptUserInvitationResponse = unknown

export type AcceptUserInvitationError = BadRequestError | ApiError | UnprocessableEntityError

export type InitPasswordResetData = {
    body: PasswordResetInitRequest
    query: {
        /**
         * Captcha challenge id
         */
        challenge: string
        /**
         * Captcha solution
         */
        input: number
    }
}

export type InitPasswordResetResponse = void

export type InitPasswordResetError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError
    | TooManyRequestsError

export type ResetPasswordData = {
    body: PasswordResetRequest
    path: {
        passwordResetToken: string
    }
}

export type ResetPasswordResponse = void

export type ResetPasswordError = BadRequestError | ApiError | UnprocessableEntityError

export type AddRoleData = {
    body: RoleRequest
}

export type AddRoleResponse = string

export type AddRoleError = BadRequestError | ApiError | UnprocessableEntityError

export type GetRolesData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetRolesResponse = {
    data: Array<RoleDto>
    pagination: Pagination
}

export type GetRolesError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateRoleData = {
    body: RoleRequest
    path: {
        roleId: string
    }
}

export type UpdateRoleResponse = void

export type UpdateRoleError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteRoleData = {
    path: {
        roleId: string
    }
}

export type DeleteRoleResponse = void

export type DeleteRoleError = BadRequestError | ApiError

export type AddEventData = {
    body: EventRequest
}

export type AddEventResponse = string

export type AddEventError = BadRequestError | ApiError | UnprocessableEntityError

export type GetEventsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetEventsResponse = {
    data: Array<EventDto>
    pagination: Pagination
}

export type GetEventsError = BadRequestError | ApiError | UnprocessableEntityError

export type GetPublicEventsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetPublicEventsResponse = {
    data: Array<EventPublicDto>
    pagination: Pagination
}

export type GetPublicEventsError = BadRequestError | ApiError | UnprocessableEntityError

export type GetEventRegistrationsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetEventRegistrationsResponse = {
    data: Array<EventRegistrationViewDto>
    pagination: Pagination
}

export type GetEventRegistrationsError = BadRequestError | ApiError | UnprocessableEntityError

export type GetEventData = {
    path: {
        eventId: string
    }
}

export type GetEventResponse = EventDto

export type GetEventError = BadRequestError | ApiError

export type UpdateEventData = {
    body: EventRequest
    path: {
        eventId: string
    }
}

export type UpdateEventResponse = void

export type UpdateEventError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteEventData = {
    path: {
        eventId: string
    }
}

export type DeleteEventResponse = void

export type DeleteEventError = BadRequestError | ApiError

export type AddEventDayData = {
    body: EventDayRequest
    path: {
        eventId: string
    }
}

export type AddEventDayResponse = string

export type AddEventDayError = BadRequestError | ApiError | UnprocessableEntityError

export type GetEventDaysData = {
    path: {
        eventId: string
    }
    query?: {
        /**
         * Optional parameter that filters by competitionId
         */
        competitionId?: string
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetEventDaysResponse = {
    data: Array<EventDayDto>
    pagination: Pagination
}

export type GetEventDaysError = BadRequestError | ApiError | UnprocessableEntityError

export type GetEventDayData = {
    path: {
        eventDayId: string
        eventId: string
    }
}

export type GetEventDayResponse = EventDayDto

export type GetEventDayError = BadRequestError | ApiError

export type UpdateEventDayData = {
    body: EventDayRequest
    path: {
        eventDayId: string
        eventId: string
    }
}

export type UpdateEventDayResponse = void

export type UpdateEventDayError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteEventDayData = {
    path: {
        eventDayId: string
        eventId: string
    }
}

export type DeleteEventDayResponse = void

export type DeleteEventDayError = BadRequestError | ApiError

export type AssignCompetitionsToEventDayData = {
    body: AssignCompetitionsToDayRequest
    path: {
        eventDayId: string
        eventId: string
    }
}

export type AssignCompetitionsToEventDayResponse = void

export type AssignCompetitionsToEventDayError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type AddCompetitionData = {
    body: CompetitionRequest
    path: {
        eventId: string
    }
}

export type AddCompetitionResponse = string

export type AddCompetitionError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionsData = {
    path: {
        eventId: string
    }
    query?: {
        /**
         * Optional parameter that filters by eventDayId
         */
        eventDayId?: string
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetCompetitionsResponse = {
    data: Array<CompetitionDto>
    pagination: Pagination
}

export type GetCompetitionsError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionData = {
    path: {
        competitionId: string
        eventId: string
    }
}

export type GetCompetitionResponse = CompetitionDto

export type GetCompetitionError = BadRequestError | ApiError

export type UpdateCompetitionData = {
    body: CompetitionRequest
    path: {
        competitionId: string
        eventId: string
    }
}

export type UpdateCompetitionResponse = void

export type UpdateCompetitionError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteCompetitionData = {
    path: {
        competitionId: string
        eventId: string
    }
}

export type DeleteCompetitionResponse = void

export type DeleteCompetitionError = BadRequestError | ApiError

export type AssignDaysToCompetitionData = {
    body: AssignDaysToCompetitionRequest
    path: {
        competitionId: string
        eventId: string
    }
}

export type AssignDaysToCompetitionResponse = void

export type AssignDaysToCompetitionError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionRegistrationsData = {
    path: {
        competitionId: string
        eventId: string
    }
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetCompetitionRegistrationsResponse = {
    data: Array<CompetitionRegistrationTeamDto>
    pagination: Pagination
}

export type GetCompetitionRegistrationsError = BadRequestError | ApiError | UnprocessableEntityError

export type AddCompetitionRegistrationData = {
    body: CompetitionRegistrationTeamUpsertDto
    path: {
        competitionId: string
        eventId: string
    }
}

export type AddCompetitionRegistrationResponse = string

export type AddCompetitionRegistrationError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateCompetitionRegistrationData = {
    body: CompetitionRegistrationTeamUpsertDto
    path: {
        competitionId: string
        competitionRegistrationId: string
        eventId: string
    }
}

export type UpdateCompetitionRegistrationResponse = void

export type UpdateCompetitionRegistrationError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type DeleteCompetitionRegistrationData = {
    path: {
        competitionId: string
        competitionRegistrationId: string
        eventId: string
    }
}

export type DeleteCompetitionRegistrationResponse = void

export type DeleteCompetitionRegistrationError = BadRequestError | ApiError

export type UpdateCompetitionSetupData = {
    body: CompetitionSetupDto
    path: {
        competitionId: string
        eventId: string
    }
}

export type UpdateCompetitionSetupResponse = void

export type UpdateCompetitionSetupError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionSetupData = {
    path: {
        competitionId: string
        eventId: string
    }
}

export type GetCompetitionSetupResponse = CompetitionSetupDto

export type GetCompetitionSetupError = BadRequestError | ApiError

export type AddDocumentsData = {
    body: {
        documentType?: string
        files?: Array<Blob | File>
    }
    path: {
        eventId: string
    }
}

export type AddDocumentsResponse = void

export type AddDocumentsError = BadRequestError | ApiError | UnprocessableEntityError

export type GetDocumentsData = {
    path: {
        eventId: string
    }
    query?: {
        documentType?: string
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetDocumentsResponse = {
    data: Array<EventDocumentDto>
    pagination: Pagination
}

export type GetDocumentsError = BadRequestError | ApiError | UnprocessableEntityError

export type DownloadDocumentData = {
    path: {
        eventDocumentId: string
        eventId: string
    }
}

export type DownloadDocumentResponse = Blob | File

export type DownloadDocumentError = BadRequestError | ApiError

export type UpdateDocumentData = {
    body: EventDocumentRequest
    path: {
        eventDocumentId: string
        eventId: string
    }
}

export type UpdateDocumentResponse = void

export type UpdateDocumentError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteDocumentData = {
    path: {
        eventDocumentId: string
        eventId: string
    }
}

export type DeleteDocumentResponse = void

export type DeleteDocumentError = BadRequestError | ApiError

export type AddCompetitionTemplateData = {
    body: CompetitionTemplateRequest
}

export type AddCompetitionTemplateResponse = string

export type AddCompetitionTemplateError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionTemplatesData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetCompetitionTemplatesResponse = {
    data: Array<CompetitionTemplateDto>
    pagination: Pagination
}

export type GetCompetitionTemplatesError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionTemplateData = {
    path: {
        competitionTemplateId: string
    }
}

export type GetCompetitionTemplateResponse = CompetitionTemplateDto

export type GetCompetitionTemplateError = BadRequestError | ApiError

export type UpdateCompetitionTemplateData = {
    body: CompetitionTemplateRequest
    path: {
        competitionTemplateId: string
    }
}

export type UpdateCompetitionTemplateResponse = void

export type UpdateCompetitionTemplateError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteCompetitionTemplateData = {
    path: {
        competitionTemplateId: string
    }
}

export type DeleteCompetitionTemplateResponse = void

export type DeleteCompetitionTemplateError = BadRequestError | ApiError

export type AddCompetitionCategoryData = {
    body: CompetitionCategoryRequest
}

export type AddCompetitionCategoryResponse = string

export type AddCompetitionCategoryError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionCategoriesResponse = {
    data: Array<CompetitionCategoryDto>
    pagination: Pagination
}

export type GetCompetitionCategoriesError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateCompetitionCategoryData = {
    body: CompetitionCategoryRequest
    path: {
        competitionCategoryId: string
    }
}

export type UpdateCompetitionCategoryResponse = void

export type UpdateCompetitionCategoryError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteCompetitionCategoryData = {
    path: {
        competitionCategoryId: string
    }
}

export type DeleteCompetitionCategoryResponse = void

export type DeleteCompetitionCategoryError = BadRequestError | ApiError

export type AddNamedParticipantData = {
    body: NamedParticipantRequest
}

export type AddNamedParticipantResponse = string

export type AddNamedParticipantError = BadRequestError | ApiError | UnprocessableEntityError

export type GetNamedParticipantsResponse = {
    data: Array<NamedParticipantDto>
    pagination: Pagination
}

export type GetNamedParticipantsError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateNamedParticipantData = {
    body: NamedParticipantRequest
    path: {
        namedParticipantId: string
    }
}

export type UpdateNamedParticipantResponse = void

export type UpdateNamedParticipantError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteNamedParticipantData = {
    path: {
        namedParticipantId: string
    }
}

export type DeleteNamedParticipantResponse = void

export type DeleteNamedParticipantError = BadRequestError | ApiError

export type NewCaptchaResponse = CaptchaDto

export type NewCaptchaError = ApiError

export type AddClubData = {
    body: ClubUpsertDto
}

export type AddClubResponse = string

export type AddClubError = BadRequestError | ApiError | UnprocessableEntityError

export type GetClubsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetClubsResponse = {
    data: Array<ClubDto>
    pagination: Pagination
}

export type GetClubsError = ApiError

export type GetClubData = {
    path: {
        clubId: string
    }
}

export type GetClubResponse = ClubDto

export type GetClubError = ApiError

export type UpdateClubData = {
    body: ClubUpsertDto
    path: {
        clubId: string
    }
}

export type UpdateClubResponse = void

export type UpdateClubError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteClubData = {
    path: {
        clubId: string
    }
}

export type DeleteClubResponse = void

export type DeleteClubError = ApiError

export type GetClubUsersData = {
    path: {
        clubId: string
    }
}

export type GetClubUsersResponse = Array<AppUserDto>

export type GetClubUsersError = ApiError

export type GetClubParticipantsData = {
    path: {
        clubId: string
    }
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetClubParticipantsResponse = {
    data: Array<ParticipantDto>
    pagination: Pagination
}

export type GetClubParticipantsError = ApiError

export type AddClubParticipantData = {
    body: ParticipantUpsertDto
    path: {
        clubId: string
    }
}

export type AddClubParticipantResponse = string

export type AddClubParticipantError = BadRequestError | ApiError | UnprocessableEntityError

export type GetClubParticipantData = {
    path: {
        clubId: string
        participantId: string
    }
}

export type GetClubParticipantResponse = ParticipantDto

export type GetClubParticipantError = ApiError

export type UpdateClubParticipantData = {
    body: ParticipantUpsertDto
    path: {
        clubId: string
        participantId: string
    }
}

export type UpdateClubParticipantResponse = void

export type UpdateClubParticipantError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteClubParticipantData = {
    path: {
        clubId: string
        participantId: string
    }
}

export type DeleteClubParticipantResponse = void

export type DeleteClubParticipantError = ApiError

export type GetClubNamesData = {
    query?: {
        /**
         * Filter for clubs, which registered for this event
         */
        eventId?: string
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetClubNamesResponse = {
    data: Array<ClubSearchDto>
    pagination: Pagination
}

export type GetClubNamesError = ApiError

export type GetRegistrationsForEventData = {
    path: {
        eventId: string
    }
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetRegistrationsForEventResponse = {
    data: Array<EventRegistrationViewDto>
    pagination: Pagination
}

export type GetRegistrationsForEventError = ApiError

export type DeleteEventRegistrationData = {
    path: {
        eventId: string
        eventRegistrationId: string
    }
}

export type DeleteEventRegistrationResponse = void

export type DeleteEventRegistrationError = BadRequestError | ApiError

export type GetEventRegistrationTemplateData = {
    path: {
        eventId: string
    }
}

export type GetEventRegistrationTemplateResponse = EventRegistrationTemplateDto

export type GetEventRegistrationTemplateError = ApiError

export type AddEventRegistrationData = {
    body: EventRegistrationUpsertDto
    path: {
        eventId: string
    }
}

export type AddEventRegistrationResponse = string

export type AddEventRegistrationError = BadRequestError | ApiError

export type GetRegistrationResultData = {
    path: {
        eventId: string
    }
    query?: {
        remake?: boolean
    }
}

export type GetRegistrationResultResponse = Blob | File

export type GetRegistrationResultError = BadRequestError | ApiError

export type AddFeeData = {
    body: FeeRequest
}

export type AddFeeResponse = string

export type AddFeeError = BadRequestError | ApiError | UnprocessableEntityError

export type GetFeesResponse = {
    data: Array<FeeDto>
    pagination: Pagination
}

export type GetFeesError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateFeeData = {
    body: FeeRequest
    path: {
        feeId: string
    }
}

export type UpdateFeeResponse = void

export type UpdateFeeError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteFeeData = {
    path: {
        feeId: string
    }
}

export type DeleteFeeResponse = void

export type DeleteFeeError = BadRequestError | ApiError

export type AddDocumentTypeData = {
    body: EventDocumentTypeRequest
}

export type AddDocumentTypeResponse = string

export type AddDocumentTypeError = BadRequestError | ApiError | UnprocessableEntityError

export type GetDocumentTypesData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetDocumentTypesResponse = {
    data: Array<EventDocumentTypeDto>
    pagination: Pagination
}

export type GetDocumentTypesError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateDocumentTypeData = {
    body: EventDocumentTypeRequest
    path: {
        eventDocumentTypeId: string
    }
}

export type UpdateDocumentTypeResponse = void

export type UpdateDocumentTypeError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteDocumentTypeData = {
    path: {
        eventDocumentTypeId: string
    }
}

export type DeleteDocumentTypeResponse = void

export type DeleteDocumentTypeError = BadRequestError | ApiError

export type GetParticipantRequirementsForEventData = {
    path: {
        eventId: string
    }
}

export type GetParticipantRequirementsForEventResponse = {
    data: Array<ParticipantRequirementForEventDto>
    pagination: Pagination
}

export type GetParticipantRequirementsForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type CheckParticipantRequirementsForEventData = {
    body: {
        config?: ParticipantRequirementCheckForEventConfigDto
        files?: Array<Blob | File>
    }
    path: {
        eventId: string
    }
}

export type CheckParticipantRequirementsForEventResponse = void

export type CheckParticipantRequirementsForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type ApproveParticipantRequirementsForEventData = {
    body: ParticipantRequirementCheckForEventUpsertDto
    path: {
        eventId: string
    }
}

export type ApproveParticipantRequirementsForEventResponse = void

export type ApproveParticipantRequirementsForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type GetActiveParticipantRequirementsForEventData = {
    path: {
        eventId: string
    }
}

export type GetActiveParticipantRequirementsForEventResponse = {
    data: Array<ParticipantRequirementForEventDto>
    pagination: Pagination
}

export type GetActiveParticipantRequirementsForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type ActivateParticipantRequirementForEventData = {
    path: {
        eventId: string
        participantRequirementId: string
    }
}

export type ActivateParticipantRequirementForEventResponse = void

export type ActivateParticipantRequirementForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type RemoveParticipantRequirementForEventData = {
    path: {
        eventId: string
        participantRequirementId: string
    }
}

export type RemoveParticipantRequirementForEventResponse = void

export type RemoveParticipantRequirementForEventError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type GetParticipantsForEventData = {
    path: {
        eventId: string
    }
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetParticipantsForEventResponse = {
    data: Array<ParticipantForEventDto>
    pagination: Pagination
}

export type GetParticipantsForEventError = ApiError

export type UpdateParticipantRequirementData = {
    body: ParticipantRequirementUpsertDto
    path: {
        participantRequirementId: string
    }
}

export type UpdateParticipantRequirementResponse = void

export type UpdateParticipantRequirementError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type DeleteParticipantRequirementData = {
    path: {
        participantRequirementId: string
    }
}

export type DeleteParticipantRequirementResponse = void

export type DeleteParticipantRequirementError = BadRequestError | ApiError

export type AddParticipantRequirementData = {
    body: ParticipantRequirementUpsertDto
}

export type AddParticipantRequirementResponse = string

export type AddParticipantRequirementError = BadRequestError | ApiError | UnprocessableEntityError

export type GetParticipantRequirementsResponse = {
    data: Array<ParticipantRequirementDto>
    pagination: Pagination
}

export type GetParticipantRequirementsError = BadRequestError | ApiError | UnprocessableEntityError

export type AddCompetitionSetupTemplateData = {
    body: CompetitionSetupTemplateRequest
}

export type AddCompetitionSetupTemplateResponse = string

export type AddCompetitionSetupTemplateError = BadRequestError | ApiError | UnprocessableEntityError

export type GetCompetitionSetupTemplatesData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetCompetitionSetupTemplatesResponse = {
    data: Array<CompetitionSetupTemplateDto>
    pagination: Pagination
}

export type GetCompetitionSetupTemplatesError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type GetCompetitionSetupTemplateData = {
    path: {
        competitionSetupTemplateId: string
    }
}

export type GetCompetitionSetupTemplateResponse = CompetitionSetupTemplateDto

export type GetCompetitionSetupTemplateError = BadRequestError | ApiError

export type UpdateCompetitionSetupTemplateData = {
    body: CompetitionSetupTemplateRequest
    path: {
        competitionSetupTemplateId: string
    }
}

export type UpdateCompetitionSetupTemplateResponse = void

export type UpdateCompetitionSetupTemplateError =
    | BadRequestError
    | ApiError
    | UnprocessableEntityError

export type DeleteCompetitionSetupTemplateData = {
    path: {
        competitionSetupTemplateId: string
    }
}

export type DeleteCompetitionSetupTemplateResponse = void

export type DeleteCompetitionSetupTemplateError = BadRequestError | ApiError

export type GetDocumentTemplatesData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetDocumentTemplatesResponse = {
    data: Array<DocumentTemplateDto>
    pagination: Pagination
}

export type GetDocumentTemplatesError = BadRequestError | ApiError | UnprocessableEntityError

export type AddDocumentTemplateData = {
    body: {
        request: DocumentTemplateRequest
        files: Array<Blob | File>
    }
}

export type AddDocumentTemplateResponse = void

export type AddDocumentTemplateError = BadRequestError | ApiError | UnprocessableEntityError

export type GetDocumentTemplateTypesResponse = Array<DocumentTypeDto>

export type GetDocumentTemplateTypesError = BadRequestError | ApiError | UnprocessableEntityError

export type AssignDocumentTemplateData = {
    body: AssignDocumentTemplateRequest
    path: {
        documentType: DocumentType
    }
}

export type AssignDocumentTemplateResponse = void

export type AssignDocumentTemplateError = BadRequestError | ApiError | UnprocessableEntityError

export type AddTaskData = {
    body: TaskUpsertDto
    path: {
        eventId: string
    }
}

export type AddTaskResponse = string

export type AddTaskError = BadRequestError | ApiError | UnprocessableEntityError

export type GetTasksData = {
    path: {
        eventId: string
    }
}

export type GetTasksResponse = {
    data: Array<TaskDto>
    pagination: Pagination
}

export type GetTasksError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateTaskData = {
    body: TaskUpsertDto
    path: {
        eventId: string
        taskId: string
    }
}

export type UpdateTaskResponse = void

export type UpdateTaskError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteTaskData = {
    path: {
        eventId: string
        taskId: string
    }
}

export type DeleteTaskResponse = void

export type DeleteTaskError = BadRequestError | ApiError

export type GetOpenTasksForUserData = {
    path: {
        userId: string
    }
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetOpenTasksForUserResponse = {
    data: Array<TaskDto>
    pagination: Pagination
}

export type GetOpenTasksForUserError = BadRequestError | ApiError | UnprocessableEntityError

export type GetBankAccountsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetBankAccountsResponse = {
    data: Array<BankAccountDto>
    pagination: Pagination
}

export type GetBankAccountsError = BadRequestError | ApiError | UnprocessableEntityError

export type AddBankAccountData = {
    body: BankAccountRequest
}

export type AddBankAccountResponse = string

export type AddBankAccountError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateBankAccountData = {
    body: BankAccountRequest
    path: {
        bankAccountId: string
    }
}

export type UpdateBankAccountResponse = void

export type UpdateBankAccountError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteBankAccountData = {
    path: {
        bankAccountId: string
    }
}

export type DeleteBankAccountResponse = void

export type DeleteBankAccountError = BadRequestError | ApiError

export type GetAssignedBankAccountData = {
    query?: {
        event?: string
    }
}

export type GetAssignedBankAccountResponse = AssignedBankAccountDto

export type GetAssignedBankAccountError = BadRequestError | ApiError | UnprocessableEntityError

export type AssignBankAccountData = {
    body: AssignBankAccountRequest
}

export type AssignBankAccountResponse = void

export type AssignBankAccountError = BadRequestError | ApiError | UnprocessableEntityError

export type ProduceInvoicesForEventRegistrationsData = {
    path: {
        eventId: string
    }
}

export type ProduceInvoicesForEventRegistrationsResponse = void

export type ProduceInvoicesForEventRegistrationsError = BadRequestError | ApiError

export type GetContactsData = {
    query?: {
        /**
         * Page size for pagination
         */
        limit?: number
        /**
         * Result offset for pagination
         */
        offset?: number
        /**
         * Filter result with space-separated search terms for pagination
         */
        search?: string
        /**
         * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
         */
        sort?: string
    }
}

export type GetContactsResponse = {
    data: Array<ContactInformationDto>
    pagination: Pagination
}

export type GetContactsError = BadRequestError | ApiError | UnprocessableEntityError

export type AddContactData = {
    body: ContactInformationRequest
}

export type AddContactResponse = string

export type AddContactError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateContactData = {
    body: ContactInformationRequest
    path: {
        contactId: string
    }
}

export type UpdateContactResponse = void

export type UpdateContactError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteContactData = {
    path: {
        contactId: string
    }
}

export type DeleteContactResponse = void

export type DeleteContactError = BadRequestError | ApiError

export type GetAssignedContactData = {
    query?: {
        event?: string
    }
}

export type GetAssignedContactResponse = AssignedContactInformationDto

export type GetAssignedContactError = BadRequestError | ApiError | UnprocessableEntityError

export type AssignContactData = {
    body: AssignContactInformationRequest
}

export type AssignContactResponse = void

export type AssignContactError = BadRequestError | ApiError | UnprocessableEntityError

export type AddWorkTypeData = {
    body: WorkTypeUpsertDto
}

export type AddWorkTypeResponse = string

export type AddWorkTypeError = BadRequestError | ApiError | UnprocessableEntityError

export type GetWorkTypesResponse = {
    data: Array<WorkTypeDto>
    pagination: Pagination
}

export type GetWorkTypesError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateWorkTypeData = {
    body: WorkTypeUpsertDto
    path: {
        workTypeId: string
    }
}

export type UpdateWorkTypeResponse = void

export type UpdateWorkTypeError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteWorkTypeData = {
    path: {
        workTypeId: string
    }
}

export type DeleteWorkTypeResponse = void

export type DeleteWorkTypeError = BadRequestError | ApiError

export type AddWorkShiftData = {
    body: WorkShiftUpsertDto
    path: {
        eventId: string
    }
}

export type AddWorkShiftResponse = string

export type AddWorkShiftError = BadRequestError | ApiError | UnprocessableEntityError

export type GetWorkShiftsData = {
    path: {
        eventId: string
    }
    query?: {
        timeFrom?: string
        timeTo?: string
    }
}

export type GetWorkShiftsResponse = {
    data: Array<WorkShiftWithAssignedUsersDto>
    pagination: Pagination
}

export type GetWorkShiftsError = BadRequestError | ApiError | UnprocessableEntityError

export type UpdateWorkShiftData = {
    body: WorkShiftUpsertDto
    path: {
        eventId: string
        workShiftId: string
    }
}

export type UpdateWorkShiftResponse = void

export type UpdateWorkShiftError = BadRequestError | ApiError | UnprocessableEntityError

export type DeleteWorkShiftData = {
    path: {
        eventId: string
        workShiftId: string
    }
}

export type DeleteWorkShiftResponse = void

export type DeleteWorkShiftError = BadRequestError | ApiError

export type GetWorkShiftsForUserData = {
    path: {
        userId: string
    }
    query?: {
        timeFrom?: string
        timeTo?: string
    }
}

export type GetWorkShiftsForUserResponse = {
    data: Array<WorkShiftWithAssignedUsersDto>
    pagination: Pagination
}

export type GetWorkShiftsForUserError = BadRequestError | ApiError | UnprocessableEntityError
