// This file is auto-generated by @hey-api/openapi-ts

export type AppUserProperties = {
    email: string
    firstname: string
    lastname: string
    roles: Array<string>
}

export type AppUserResponse = {
    id: string
    properties: AppUserProperties
}

export type LoginRequest = {
    email: string
    password: string
}

export type LoginResponse = {
    privilegesGlobal: Array<Privilege>
    privilegesBound: Array<Privilege>
}

/**
 * Page size for pagination
 */
export type Parameterlimit = number

/**
 * Result offset for pagination
 */
export type Parameteroffset = number

/**
 * Filter result with space-separated search terms for pagination
 */
export type Parametersearch = string

/**
 * Fields with direction (as JSON [{field: <field>, direction: ASC | DESC}, ...]) sorting result for pagination
 */
export type Parametersort = string

export type Privilege = 'USER_VIEW' | 'USER_EDIT' | 'ROLE_VIEW' | 'ROLE_EDIT'

export type UserLoginData = {
    body: LoginRequest
}

export type UserLoginResponse = LoginResponse

export type UserLoginError = string
