CREATE TABLE CLUB
(
    ID         UUID      NOT NULL PRIMARY KEY,
    NAME       TEXT      NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY UUID      REFERENCES APP_USER ON DELETE SET NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY UUID      REFERENCES APP_USER ON DELETE SET NULL
);

CREATE TYPE GENDER AS ENUM ('M', 'F', 'O');

CREATE TABLE PARTICIPANT
(
    ID                 UUID                 NOT NULL PRIMARY KEY,
    CLUB               UUID REFERENCES CLUB NOT NULL,
    FIRSTNAME          TEXT                 NOT NULL,
    LASTNAME           TEXT                 NOT NULL,
    YEAR               INTEGER,
    GENDER             GENDER               NOT NULL,
    PHONE              TEXT,
    EXTERNAL           BOOLEAN              NOT NULL DEFAULT FALSE,
    EXTERNAL_CLUB_NAME TEXT,
    CREATED_AT         TIMESTAMP            NOT NULL,
    CREATED_BY         UUID                 REFERENCES APP_USER ON DELETE SET NULL,
    UPDATED_AT         TIMESTAMP            NOT NULL,
    UPDATED_BY         UUID                 REFERENCES APP_USER ON DELETE SET NULL
        CONSTRAINT CHK_EXTERN_HAS_CLUB_NAME CHECK ((EXTERNAL = TRUE AND EXTERNAL_CLUB_NAME IS NOT NULL) OR
                                                   (EXTERNAL = FALSE AND EXTERNAL_CLUB_NAME IS NULL))
);

CREATE INDEX ON PARTICIPANT (CLUB);

CREATE TABLE EVENT_REGISTRATION
(
    ID                   UUID PRIMARY KEY,
    EVENT                UUID REFERENCES EVENT NOT NULL,
    CLUB                 UUID REFERENCES CLUB  NOT NULL,
    OPTIONAL_FEE_CHECKED BOOLEAN               NOT NULL DEFAULT FALSE,
    CREATED_AT           TIMESTAMP             NOT NULL,
    CREATED_BY           UUID                  REFERENCES APP_USER ON DELETE SET NULL,
    UPDATED_AT           TIMESTAMP             NOT NULL,
    UPDATED_BY           UUID                  REFERENCES APP_USER ON DELETE SET NULL
);
CREATE UNIQUE INDEX EVENT_REGISTRATION_UNIQUE_FOR_CLUB ON EVENT_REGISTRATION (EVENT, CLUB);

CREATE INDEX ON EVENT_REGISTRATION (CLUB);
CREATE INDEX ON EVENT_REGISTRATION (EVENT);

CREATE TABLE EVENT_DAY_REGISTRATION
(
    ID                   UUID      NOT NULL PRIMARY KEY,
    EVENT_DAY            UUID      NOT NULL REFERENCES EVENT_DAY,
    CLUB                 UUID      NOT NULL REFERENCES CLUB,
    OPTIONAL_FEE_CHECKED BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT           TIMESTAMP NOT NULL,
    CREATED_BY           UUID      REFERENCES APP_USER ON DELETE SET NULL,
    UPDATED_AT           TIMESTAMP NOT NULL,
    UPDATED_BY           UUID      REFERENCES APP_USER ON DELETE SET NULL
);

CREATE INDEX ON EVENT_DAY_REGISTRATION (EVENT_DAY);
CREATE INDEX ON EVENT_DAY_REGISTRATION (CLUB);

CREATE TABLE RACE_REGISTRATION
(
    ID                   UUID      NOT NULL PRIMARY KEY,
    RACE                 UUID      NOT NULL REFERENCES RACE,
    CLUB                 UUID      NOT NULL REFERENCES CLUB,
    NAME                 TEXT,
    OPTIONAL_FEE_CHECKED BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT           TIMESTAMP NOT NULL,
    CREATED_BY           UUID      REFERENCES APP_USER ON DELETE SET NULL,
    UPDATED_AT           TIMESTAMP NOT NULL,
    UPDATED_BY           UUID      REFERENCES APP_USER ON DELETE SET NULL,
    UNIQUE (RACE, CLUB, NAME)
);

CREATE INDEX ON RACE_REGISTRATION (RACE);
CREATE INDEX ON RACE_REGISTRATION (CLUB);

CREATE TABLE RACE_REGISTRATION_PARTICIPANT
(
    RACE_REGISTRATION UUID NOT NULL REFERENCES RACE_REGISTRATION ON DELETE CASCADE,
    PARTICIPANT       UUID NOT NULL REFERENCES PARTICIPANT,
    PRIMARY KEY (RACE_REGISTRATION, PARTICIPANT)
);

CREATE TABLE RACE_REGISTRATION_NAMED_PARTICIPANT
(
    RACE_REGISTRATION UUID NOT NULL REFERENCES RACE_REGISTRATION ON DELETE CASCADE,
    NAMED_PARTICIPANT UUID NOT NULL REFERENCES NAMED_PARTICIPANT,
    PARTICIPANT       UUID NOT NULL REFERENCES PARTICIPANT,

    PRIMARY KEY (RACE_REGISTRATION, PARTICIPANT)
);

CREATE INDEX ON RACE_REGISTRATION_NAMED_PARTICIPANT (NAMED_PARTICIPANT);
