package de.lambda9.ready2race.backend.calls.responses

enum class ErrorCode {
    CANNOT_ASSIGN_ROLES,
    CAPTCHA_WRONG,
    EMAIL_IN_USE,
    EVENT_REGISTRATION_ONGOING,
    INVOICES_ALREADY_PRODUCED,
    NO_ASSIGNED_PAYEE_INFORMATION,
    NO_ASSIGNED_CONTACT_INFORMATION,

    FILE_ERROR,

    SPREADSHEET_MALFORMED,
    SPREADSHEET_NO_HEADERS,
    SPREADSHEET_COLUMN_UNKNOWN,
    SPREADSHEET_CELL_BLANK,
    SPREADSHEET_WRONG_CELL_TYPE,
    SPREADSHEET_UNPARSABLE_STRING,

    WRONG_TEAM_COUNT,
    DUPLICATE_START_NUMBERS,
    DUPLICATE_PLACES,
    PLACES_UNCONTINUOUS
}