package de.lambda9.ready2race.backend.calls.responses

enum class ErrorCode {
    CANNOT_ASSIGN_ROLES,
    CAPTCHA_WRONG,
    EMAIL_IN_USE,
    EVENT_REGISTRATION_ONGOING,
    INVOICES_ALREADY_PRODUCED,
    NO_ASSIGNED_PAYEE_INFORMATION,
    NO_ASSIGNED_CONTACT_INFORMATION,
    CE_SETUP_HAS_NO_ROUNDS,
    CE_FINAL_ROUND_ALREADY_CREATED,
    CE_NO_SETUP_MATCHES_FOR_NEXT_ROUND,
    CE_NO_REGISTRATIONS_FOR_COMPETITION,
    CE_NOT_ENOUGH_TEAM_SPACE_IN_FIRST_ROUND,
    CE_NOT_ALL_PLACES_SET
}