package de.lambda9.ready2race.backend.calls.responses

enum class ErrorCode {
    CANNOT_ASSIGN_ROLES,
    CAPTCHA_WRONG,
    EMAIL_IN_USE,
    INVOICES_ALREADY_PRODUCED,
    NO_ASSIGNED_PAYEE_INFORMATION,
    NO_ASSIGNED_CONTACT_INFORMATION,

    EVENT_REGISTRATION_ONGOING,
    EVENT_REGISTRATION_CLOSED,
    EVENT_REGISTRATION_UPSERT_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_TEAM_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_COMPETITION_NOT_FOUND,
    EVENT_REGISTRATION_NAMED_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_FEE_NOT_FOUND,
    EVENT_REGISTRATION_RATING_CATEGORY_NOT_FOUND,
    EVENT_REGISTRATION_RATING_CATEGORY_MISSING,
    EVENT_REGISTRATION_AGE_REQUIREMENT_NOT_MET,
    EVENT_REGISTRATION_PARTICIPANT_DUPLICATE_IN_COMPETITION,

    FILE_ERROR,

    SPREADSHEET_MALFORMED,
    SPREADSHEET_NO_HEADERS,
    SPREADSHEET_COLUMN_UNKNOWN,
    SPREADSHEET_CELL_BLANK,
    SPREADSHEET_WRONG_CELL_TYPE,
    SPREADSHEET_UNPARSABLE_STRING,

    WRONG_TEAM_COUNT,
    DUPLICATE_START_NUMBERS,
    DUPLICATE_PLACES,
    PLACES_UNCONTINUOUS,

    PARTICIPANT_IMPORT_UNKNOWN_GENDER_VALUE
}